### ISSUE TITLE
Device compatibility question

### ISSUE THREAD

**Issue by HJ959** [generalelectrix/pyenttec#6]
So I've tried to no avail with a cheap USB-DMX interface, thinking I'll need to get an Enttec Pro,

My question is has anyone tried the Open DMX USB from Enttec (the cheaper one) with this module?

Cheers

**Comment by willstott101** [comment]
Did you manage to make it work?

**Comment by generalelectrix** [comment]
The open usb (aka the cheaper enttec) is built on completely different
serial hardware and is not compatible with this library.  I also wouldn’t
recommend it.

**Comment by HJ959** [comment]
Thanks for your help!
